import java.lang.Exception

class CoreClass {
  def x = 2+ 2
  val a = x

}
